version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: veritas-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=veritas
    volumes:
      - ./mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - veritas-network

  mongo-express:
    image: mongo-express:latest
    container_name: veritas-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - veritas-network

networks:
  veritas-network:
    name: veritas-network 