---
name: Veritas CI/CD

# This workflow handles CI/CD for the Veritas open source project
# Note on secrets:
# - For basic CI (lint, test, build), no secrets are required
# - For GCP deployment, the following secrets are needed:
#   - GCP_PROJECT_ID: Google Cloud project ID
#   - GCR_JSON_KEY: JSON key for Google Container Registry
#   - GCP_SA_KEY: Service account key for GCP authentication
#   - GKE_CLUSTER_NAME: Name of the GKE cluster
#   - GKE_CLUSTER_LOCATION: Location of the GKE cluster
# Contributors without access to these secrets can still run lint, test, and build tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run TypeScript type checking
        run: npm run type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm test
        
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build API
        run: npm run build:api
        
      - name: Build Frontend
        run: npm run build:frontend
        
      - name: Upload API build artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-build
          path: apps/api/dist
          
      - name: Upload Frontend build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: apps/visualization-showcase/dist

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    # Only run this job on the main branch
    # Note: This job requires GCP_PROJECT_ID and GCR_JSON_KEY secrets
    # It will fail if these secrets are not available in the repository
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Check required secrets
        id: check_secrets
        run: |
          if [ -n "${{ secrets.GCP_PROJECT_ID }}" ] && [ -n "${{ secrets.GCR_JSON_KEY }}" ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
            echo "Required secrets are missing. Some steps will be skipped."
            echo "For open source contributors: Docker publishing requires GCP_PROJECT_ID and GCR_JSON_KEY secrets."
          fi
      
      - name: Download API build artifact
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: actions/download-artifact@v3
        with:
          name: api-build
          path: apps/api/dist
          
      - name: Download Frontend build artifact
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: apps/visualization-showcase/dist
          
      - name: Set up Docker Buildx
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Google Container Registry
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
          
      - name: Build and push API Docker image
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-api:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-api:latest
          
      - name: Build and push Frontend Docker image
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/visualization-showcase/Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-frontend:${{ github.sha }},gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-frontend:latest

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: docker
    # Only run this job on the main branch
    # Note: This job requires GCP_SA_KEY, GKE_CLUSTER_NAME, GKE_CLUSTER_LOCATION, and GCP_PROJECT_ID secrets
    # It will fail if these secrets are not available in the repository
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Check required secrets
        id: check_secrets
        run: |
          if [ -n "${{ secrets.GCP_SA_KEY }}" ] && [ -n "${{ secrets.GKE_CLUSTER_NAME }}" ] && [ -n "${{ secrets.GKE_CLUSTER_LOCATION }}" ] && [ -n "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "has_secrets=true" >> $GITHUB_OUTPUT
          else
            echo "has_secrets=false" >> $GITHUB_OUTPUT
            echo "Required secrets are missing. Some steps will be skipped."
            echo "For open source contributors: Deployment requires GCP_SA_KEY, GKE_CLUSTER_NAME, GKE_CLUSTER_LOCATION, and GCP_PROJECT_ID secrets."
          fi
      
      - name: Setup gcloud CLI
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Setup kubectl
        if: steps.check_secrets.outputs.has_secrets == 'true'
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Update Kubernetes manifests
        if: steps.check_secrets.outputs.has_secrets == 'true'
        run: |
          sed -i 's|gcr.io/PROJECT_ID/veritas-api:latest|gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-api:${{ github.sha }}|g' kubernetes/veritas-deployment.yaml
          sed -i 's|gcr.io/PROJECT_ID/veritas-frontend:latest|gcr.io/${{ secrets.GCP_PROJECT_ID }}/veritas-frontend:${{ github.sha }}|g' kubernetes/veritas-deployment.yaml
          
      - name: Deploy to GKE
        if: steps.check_secrets.outputs.has_secrets == 'true'
        run: |
          kubectl apply -f kubernetes/veritas-deployment.yaml
          
      - name: Verify deployment
        if: steps.check_secrets.outputs.has_secrets == 'true'
        run: |
          kubectl rollout status deployment/veritas-api -n veritas
          kubectl rollout status deployment/veritas-frontend -n veritas 