---
name: Security Scanning

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  dependency-check:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true
        
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  code-scanning:
    name: Code Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Run ESLint Security Plugin
        run: |
          npm ci
          npm install -g eslint @typescript-eslint/parser eslint-plugin-security
          eslint --plugin security --ext .js,.ts,.tsx . -c .eslintrc.js

  container-scanning:
    name: Container Security Scan
    runs-on: ubuntu-latest
    needs: [dependency-check, code-scanning]
    steps:
      - uses: actions/checkout@v3
      
      - name: Build API Docker image
        run: docker build -t veritas-api:${{ github.sha }} -f apps/api/Dockerfile .
        
      - name: Build Frontend Docker image
        run: docker build -t veritas-frontend:${{ github.sha }} -f apps/visualization-showcase/Dockerfile .
        
      - name: Run Trivy vulnerability scanner on API image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: veritas-api:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-api.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Run Trivy vulnerability scanner on Frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: veritas-frontend:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results-frontend.sarif'
          severity: 'CRITICAL,HIGH'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-api.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results-frontend.sarif'

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  security-report:
    name: Generate Security Report
    runs-on: ubuntu-latest
    needs: [dependency-check, code-scanning, container-scanning, secret-scanning]
    steps:
      - name: Create Security Report
        run: |
          echo "# Security Scan Report" > security-report.md
          echo "## Scan Date: $(date)" >> security-report.md
          echo "## Repository: ${{ github.repository }}" >> security-report.md
          echo "## Commit: ${{ github.sha }}" >> security-report.md
          echo "## Scans Performed:" >> security-report.md
          echo "- Dependency Vulnerability Scan" >> security-report.md
          echo "- Code Security Scan" >> security-report.md
          echo "- Container Security Scan" >> security-report.md
          echo "- Secret Scanning" >> security-report.md
          echo "## Results" >> security-report.md
          echo "Please check the GitHub Security tab for detailed results." >> security-report.md
          
      - name: Upload Security Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: security-report.md 